// 创建简历页面内容
export function createAboutPage(): string[] {
  return [
    '<div class="resume">',
    '  <div class="resume-header">',
    '    <h1>个人简历</h1>',
    '    <br/>',
    '    <div class="personal-info">',
    '    <h2>基本信息</h2>',
    '      <div class="info-item"><strong>姓名：</strong>李斯</div>',
    '      <div class="info-item"><strong>性别：</strong>男</div>',
    '      <div class="info-item"><strong>年龄：</strong>29岁</div>',
    '      <div class="info-item"><strong>学历：</strong>本科</div>',
    '      <div class="info-item"><strong>学校：</strong>中南大学</div>',
    '      <div class="info-item"><strong>专业：</strong>信息与计算科学系</div>',
    '      <div class="info-item"><strong>工作年限：</strong>6年</div>',
    '      <div class="info-item"><strong>职位：</strong>Java P6 & React+TS+Nextjs+Nestjs(Hono.js)全栈开发</div>',
    '      <div class="info-item"><strong>期望薪资：</strong>税前月薪20k~25k</div>',
    '    </div>',
    '    <br/>',
    '    <div class="contact-info">',
    '    <h2>联系信息</h2>',
    '      <div class="info-item"><strong>手机：</strong>17363859671</div>',
    '      <div class="info-item"><strong>Email：</strong>aspirelisi@gmail.com（392710909@qq.com）</div>',
    '      <div class="info-item"><strong>微信号：</strong>17363859671</div>',
    '      <div class="info-item"><strong>QQ：</strong>392710909</div>',
    '    </div>',
    '  </div>',
    '',
    '    <br/>',
    '  <div class="content-section">',
    '    <h2>技能清单</h2>',
    '    <br/>',
    '    <div class="skills-grid">',
    '      <div class="skill-category">',
    '        <h3>系统架构</h3>',
    '        <ul>',
    '          <li>有丰富的系统单元化设计、微服务拆分和改造经验，对于系统架构扩展有一定的沉淀和理解</li>',
    '          <li>对于分布式服务开发和维护有一定的经验</li>',
    '          <li>对于超大规模用户和数据量系统开发有一定的把握能力</li>',
    '          <li>对于复杂系统和需求设计开发具有良好的拆分和分解能力</li>',
    '          <li>丰富的大规模 to C业务需求开发经验</li>',
    '        </ul>',
    '      </div>',
    '    <br/>',
    '      <div class="skill-category">',
    '        <h3>后端技术</h3>',
    '        <ul>',
    '          <li>熟练使用spring cloud全家桶进行微服务设计和开发</li>',
    '          <li>熟练掌握Java语言，了解JVM底层，熟悉多线程编程，有一定实践经验</li>',
    '          <li>熟练使用Spring、SpringMVC、MyBatis开发框架，熟悉SpringBoot框架</li>',
    '          <li>熟练掌握Mysql数据库使用，并且有一定的分析和调优经验，了解主从和高可用架构</li>',
    '          <li>熟悉非关系型数据库MongoDB，有分片分表实践经验</li>',
    '          <li>熟悉Redis，并且有相关规范和调优实战经验</li>',
    '          <li>熟悉Kafka消息队列的基本原理和使用场景</li>',
    '          <li>熟悉分布式任务调度框架Quartz</li>',
    '        </ul>',
    '      </div>',
    '    <br/>',

    '      <div class="skill-category">',
    '        <h3>前端技术</h3>',
    '        <ul>',
    '          <li>熟悉React+TS+Nextjs+Nestjs(Hono.js)全栈独立开发</li>',
    '        </ul>',
    '      </div>',
    '    <br/>',

    '      <div class="skill-category">',
    '        <h3>开发工具</h3>',
    '        <ul>',
    '          <li>熟练使用eclipse/idea编程工具，具有良好的编程习惯</li>',
    '          <li>熟练使用PowerDesigner建模工具进行数据库相关建模，有良好的规范习惯</li>',
    '          <li>熟练使用Chrome等工具进行代码调试</li>',
    '          <li>熟练使用git版本控制工具的使用，有良好的使用习惯</li>',
    '          <li>熟悉SecureCRT工具，熟悉基本的Linux命令，掌握日志追踪和查找规范和方法</li>',
    '        </ul>',
    '      </div>',
    '    <br/>',

    '      <div class="skill-category">',
    '        <h3>其他技能</h3>',
    '        <ul>',
    '          <li>熟悉分布式服务注册发现中心Zookeeper、Consul的基本原理和使用</li>',
    '          <li>了解Docker、rancher的基本使用和部署操作</li>',
    '          <li>熟悉中小型企业规模服务器搭架和构建部署</li>',
    '        </ul>',
    '      </div>',
    '    </div>',
    '  </div>',
    '',
    '    <br/>',

    '  <div class="content-section">',
    '    <h2>工作经历</h2>',
    '    <div class="timeline">',
    '      <div class="timeline-item">',
    '        <div class="timeline-header">',
    '          <h3>倍立健生物科技</h3>',
    '          <span class="timeline-date">2024年6月 ~ 2025年6月</span>',
    '        </div>',
    '        <div class="timeline-content">',
    '          <h4>自研CRM</h4>',
    '          <ul>',
    '            <li>主导自研的 crm 后台开发工作，独立完成 api admin web 开发</li>',
    '          </ul>',
    '        </div>',
    '      </div>',
    '',
    '    <br/>',
    '      <div class="timeline-item">',
    '        <div class="timeline-header">',
    '          <h3>湖南福米科技</h3>',
    '          <span class="timeline-date">2020年6月 ~ 2023年12月</span>',
    '        </div>',
    '        <div class="timeline-content">',
    '          <h4>北美证券市场交易平台（千万级用户7*24小时资产交易平台）</h4>',
    '          <ul>',
    '            <li>主导北美证券市场自研产品webull app账户系统开户、合规业务的设计和开发工作，用户生命周期管理，多品类交易权限，合规管控，风险管控等等</li>',
    '            <li>参与webull账单、盈亏、出入金和转仓系统的业务开发工作，与自研第三方清算商对接，涉及用户资产转移和盈亏计算，账单生成等等业务</li>',
    '            <li>参与公司级自研清算商迁移项目，全平台百万级用户迁移改造</li>',
    '            <li>参与交易下单链路重构和改造开发工作，因为展业需求，对老业务系统进行整体的架构调整和升级当中的必然旧有链路迁移改造工作</li>',
    '            <li>参与系统单元化（支持横向无限制业务扩展支撑）改造升级开发工作，为适应超大规模用户横向扩展，降低系统运营成本，解决中间件无法横向扩展问题，以及灾备需要而进行的系统改造</li>',
    '            <li>主导7.0网关接口升级项目，对接公司客户端团队，包括ios、android、h5、qt、web 多端各业务场景接口的重构、迁移、整合工作</li>',
    '            <li>主导公司加拿大地区展业账户系统的设计开发工作，包括账户、权限管控、风控相关的业务</li>',
    '          </ul>',
    '        </div>',
    '      </div>',
    '',
    '    <br/>',

    '      <div class="timeline-item">',
    '        <div class="timeline-header">',
    '          <h3>湖南草花互动网络科技有限公司</h3>',
    '          <span class="timeline-date">2018年3月 ~ 2020年3月</span>',
    '        </div>',
    '        <div class="timeline-content">',
    '          <h4>投放系统项目（百万级手游平台）</h4>',
    '          <ul>',
    '            <li>参与今日头条、腾讯广电通、百度、UC等30+媒体广告服务商对接，打造一体化投放平台，系统得到今日头条等媒体认可，处于行业前列</li>',
    '            <li>主导开发和维护第三方媒体广告数据监测服务（PV日均600W+，峰值7000W+）</li>',
    '            <li>2019年作为项目组核心程序员，参与开发和维护公司投放系统业务。不但完成内部管理系统的版本迭代需求。利用开发间隙，结合业务解析现有系统实现。优化线上广告点击监测业务Redis集群内存超过65%。并且在不影响现有系统的情况下，结合MongoDB将点击匹配数据存留从1天延长到7天，有效提高点击归因率。</li>',
    '            <li>主导开发和维护公司爬虫系统，熟练使用jsoup等爬虫框架和自动化测试框架，熟悉业务数据埋点采集相关流程</li>',
    '            <li>从零主导开发搭建公司DMP自动化系统，参与迭代维护公司数据仓库项目，熟悉Hadoop和Hive等大数据组件清洗业务数据的流程</li>',
    '            <li>主导技术后台统计相关数据稽查业务，熟练使用sql进行数据统计核查</li>',
    '          </ul>',
    '        </div>',
    '      </div>',
    '',
    '    <br/>',

    '      <div class="timeline-item">',
    '        <div class="timeline-header">',
    '          <h3>湖南瑞药网络科技有限公司</h3>',
    '          <span class="timeline-date">2017年4月 ~ 2018年3月</span>',
    '        </div>',
    '        <div class="timeline-content">',
    '          <h4>药易得APP后台管理系统项目</h4>',
    '          <ul>',
    '            <li>参与App数据后台管理系统数据服务研发，以及相关溯源方案的设计</li>',
    '            <li>主导管理系统药品百科等模块的设计和开发工作</li>',
    '            <li>使用缓存和CDN加速，极大提高药品百科加载速率</li>',
    '          </ul>',
    '        </div>',
    '      </div>',
    '    </div>',
    '  </div>',
    '',
    '    <br/>',
    '  <div class="content-section">',
    '    <h2>个人特点</h2>',
    '    <ul class="personal-traits">',
    '      <li>性格外向，慷慨健谈，具有良好的沟通交流能力，热爱分享，有耐心，善于说教</li>',
    '      <li>有很好的抗压能力，遇事不甩锅不逃避</li>',
    '      <li>热爱技术，优良的需求分析和表达能力，学习适应能力</li>',
    '      <li>较强的责任心和良好的团队合作精神</li>',
    '      <li>热爱分享，在团队中曾分享过业务和技术沉淀</li>',
    '      <li>兴趣广泛（旅行、摄影，极限飞盘运动等等）</li>',
    '    </ul>',
    '  </div>',
    '</div>'
  ];
} 