// 创建简历页面内容
export function createAboutInfo(): string[] {
  return [
    '<div class="resume">',
    '  <div class="resume-header">',
    "    <h1>个人简历</h1>",
    "    <br/>",
    '    <div class="personal-info">',
    "    <h2>基本信息</h2>",
    '      <div class="info-item"><strong>姓名：</strong>李斯</div>',
    '      <div class="info-item"><strong>性别：</strong>男</div>',
    '      <div class="info-item"><strong>年龄：</strong>29岁</div>',
    '      <div class="info-item"><strong>学历：</strong>本科</div>',
    '      <div class="info-item"><strong>学校：</strong>中南大学</div>',
    '      <div class="info-item"><strong>专业：</strong>信息与计算科学系</div>',
    '      <div class="info-item"><strong>工作年限：</strong>6年</div>',
    '      <div class="info-item"><strong>职位：</strong>Java P6 & React+TS+Nextjs+Nestjs(Hono.js)全栈开发</div>',
    '      <div class="info-item"><strong>期望薪资：</strong>税前月薪20k~25k</div>',
    "    </div>",
    "    <br/>",
    '    <div class="contact-info">',
    "    <h2>联系信息</h2>",
    '      <div class="info-item"><strong>手机：</strong>17363859671</div>',
    '      <div class="info-item"><strong>Email：</strong>aspirelisi@gmail.com（392710909@qq.com）</div>',
    '      <div class="info-item"><strong>微信号：</strong>17363859671</div>',
    '      <div class="info-item"><strong>QQ：</strong>392710909</div>',
    "    </div>",
    "  </div>",
    "",
    "    <br/>",
    '  <div class="content-section">',
    "    <h2>技能清单</h2>",
    "    <br/>",
    '    <div class="skills-grid">',
    '      <div class="skill-category">',
    "        <h3>系统架构</h3>",
    "        <ul>",
    "          <li>有丰富的系统单元化设计、微服务拆分和改造经验，对于系统架构扩展有一定的沉淀和理解</li>",
    "          <li>对于分布式服务开发和维护有一定的经验</li>",
    "          <li>对于超大规模用户和数据量系统开发有一定的把握能力</li>",
    "          <li>对于复杂系统和需求设计开发具有良好的拆分和分解能力</li>",
    "          <li>丰富的大规模 to C业务需求开发经验</li>",
    "        </ul>",
    "      </div>",
    "    <br/>",
    '      <div class="skill-category">',
    "        <h3>后端技术</h3>",
    "        <ul>",
    "          <li>熟练使用spring cloud全家桶进行微服务设计和开发</li>",
    "          <li>熟练掌握Java语言，了解JVM底层，熟悉多线程编程，有一定实践经验</li>",
    "          <li>熟练使用Spring、SpringMVC、MyBatis开发框架，熟悉SpringBoot框架</li>",
    "          <li>熟练掌握Mysql数据库使用，并且有一定的分析和调优经验，了解主从和高可用架构</li>",
    "          <li>熟悉非关系型数据库MongoDB，有分片分表实践经验</li>",
    "          <li>熟悉Redis，并且有相关规范和调优实战经验</li>",
    "          <li>熟悉Kafka消息队列的基本原理和使用场景</li>",
    "          <li>熟悉分布式任务调度框架Quartz</li>",
    "        </ul>",
    "      </div>",
    "    <br/>",

    '      <div class="skill-category">',
    "        <h3>前端技术</h3>",
    "        <ul>",
    "          <li>熟悉React+TS+Nextjs+Nestjs(Hono.js)全栈独立开发</li>",
    "        </ul>",
    "      </div>",
    "    <br/>",

    '      <div class="skill-category">',
    "        <h3>开发工具</h3>",
    "        <ul>",
    "          <li>熟练使用eclipse/idea编程工具，具有良好的编程习惯</li>",
    "          <li>熟练使用PowerDesigner建模工具进行数据库相关建模，有良好的规范习惯</li>",
    "          <li>熟练使用Chrome等工具进行代码调试</li>",
    "          <li>熟练使用git版本控制工具的使用，有良好的使用习惯</li>",
    "          <li>熟悉SecureCRT工具，熟悉基本的Linux命令，掌握日志追踪和查找规范和方法</li>",
    "        </ul>",
    "      </div>",
    "    <br/>",

    '      <div class="skill-category">',
    "        <h3>其他技能</h3>",
    "        <ul>",
    "          <li>熟悉分布式服务注册发现中心Zookeeper、Consul的基本原理和使用</li>",
    "          <li>了解Docker、rancher的基本使用和部署操作</li>",
    "          <li>熟悉中小型企业规模服务器搭架和构建部署</li>",
    "        </ul>",
    "      </div>",
    "    </div>",
    "  </div>",
    "",
    "    <br/>",

    '  <div class="content-section">',
    "    <h2>工作经历</h2>",
    '    <div class="timeline">',
    '      <div class="timeline-item">',
    '        <div class="timeline-header">',
    "          <h3>倍立健生物科技</h3>",
    '          <span class="timeline-date">2024年6月 ~ 2025年6月</span>',
    "        </div>",
    '        <div class="timeline-content">',
    "          <h4>自研CRM</h4>",
    "          <ul>",
    "            <li>主导自研的 crm 后台开发工作，独立完成 api admin web 开发</li>",
    "          </ul>",
    "        </div>",
    "      </div>",
    "",
    "    <br/>",
    '      <div class="timeline-item">',
    '        <div class="timeline-header">',
    "          <h3>湖南福米科技</h3>",
    '          <span class="timeline-date">2020年6月 ~ 2023年12月</span>',
    "        </div>",
    '        <div class="timeline-content">',
    "          <h4>北美证券市场交易平台（千万级用户7*24小时资产交易平台）</h4>",
    "          <ul>",
    "            <li>主导北美证券市场自研产品webull app账户系统开户、合规业务的设计和开发工作，用户生命周期管理，多品类交易权限，合规管控，风险管控等等</li>",
    "            <li>参与webull账单、盈亏、出入金和转仓系统的业务开发工作，与自研第三方清算商对接，涉及用户资产转移和盈亏计算，账单生成等等业务</li>",
    "            <li>参与公司级自研清算商迁移项目，全平台百万级用户迁移改造</li>",
    "            <li>参与交易下单链路重构和改造开发工作，因为展业需求，对老业务系统进行整体的架构调整和升级当中的必然旧有链路迁移改造工作</li>",
    "            <li>参与系统单元化（支持横向无限制业务扩展支撑）改造升级开发工作，为适应超大规模用户横向扩展，降低系统运营成本，解决中间件无法横向扩展问题，以及灾备需要而进行的系统改造</li>",
    "            <li>主导7.0网关接口升级项目，对接公司客户端团队，包括ios、android、h5、qt、web 多端各业务场景接口的重构、迁移、整合工作</li>",
    "            <li>主导公司加拿大地区展业账户系统的设计开发工作，包括账户、权限管控、风控相关的业务</li>",
    "          </ul>",
    "        </div>",
    "      </div>",
    "",
    "    <br/>",

    '      <div class="timeline-item">',
    '        <div class="timeline-header">',
    "          <h3>湖南草花互动网络科技有限公司</h3>",
    '          <span class="timeline-date">2018年3月 ~ 2020年3月</span>',
    "        </div>",
    '        <div class="timeline-content">',
    "          <h4>投放系统项目（百万级手游平台）</h4>",
    "          <ul>",
    "            <li>参与今日头条、腾讯广电通、百度、UC等30+媒体广告服务商对接，打造一体化投放平台，系统得到今日头条等媒体认可，处于行业前列</li>",
    "            <li>主导开发和维护第三方媒体广告数据监测服务（PV日均600W+，峰值7000W+）</li>",
    "            <li>2019年作为项目组核心程序员，参与开发和维护公司投放系统业务。不但完成内部管理系统的版本迭代需求。利用开发间隙，结合业务解析现有系统实现。优化线上广告点击监测业务Redis集群内存超过65%。并且在不影响现有系统的情况下，结合MongoDB将点击匹配数据存留从1天延长到7天，有效提高点击归因率。</li>",
    "            <li>主导开发和维护公司爬虫系统，熟练使用jsoup等爬虫框架和自动化测试框架，熟悉业务数据埋点采集相关流程</li>",
    "            <li>从零主导开发搭建公司DMP自动化系统，参与迭代维护公司数据仓库项目，熟悉Hadoop和Hive等大数据组件清洗业务数据的流程</li>",
    "            <li>主导技术后台统计相关数据稽查业务，熟练使用sql进行数据统计核查</li>",
    "          </ul>",
    "        </div>",
    "      </div>",
    "",
    "    <br/>",

    '      <div class="timeline-item">',
    '        <div class="timeline-header">',
    "          <h3>湖南瑞药网络科技有限公司</h3>",
    '          <span class="timeline-date">2017年4月 ~ 2018年3月</span>',
    "        </div>",
    '        <div class="timeline-content">',
    "          <h4>药易得APP后台管理系统项目</h4>",
    "          <ul>",
    "            <li>参与App数据后台管理系统数据服务研发，以及相关溯源方案的设计</li>",
    "            <li>主导管理系统药品百科等模块的设计和开发工作</li>",
    "            <li>使用缓存和CDN加速，极大提高药品百科加载速率</li>",
    "          </ul>",
    "        </div>",
    "      </div>",
    "    </div>",
    "  </div>",
    "",
    "    <br/>",
    '  <div class="content-section">',
    "    <h2>个人特点</h2>",
    '    <ul class="personal-traits">',
    "      <li>性格外向，慷慨健谈，具有良好的沟通交流能力，热爱分享，有耐心，善于说教</li>",
    "      <li>有很好的抗压能力，遇事不甩锅不逃避</li>",
    "      <li>热爱技术，优良的需求分析和表达能力，学习适应能力</li>",
    "      <li>较强的责任心和良好的团队合作精神</li>",
    "      <li>热爱分享，在团队中曾分享过业务和技术沉淀</li>",
    "      <li>兴趣广泛（旅行、摄影，极限飞盘运动等等）</li>",
    "    </ul>",
    "  </div>",
    "</div>",
  ];
}

// 创建英文简历页面内容
export function createAboutInfoEN(): string[] {
  return [
    '<div class="resume">',
    '  <div class="resume-header">',
    "    <h1>Resume</h1>",
    "    <br/>",
    '    <div class="personal-info">',
    "    <h2>Personal Information</h2>",
    '      <div class="info-item"><strong>Name:</strong>Li Si</div>',
    '      <div class="info-item"><strong>Gender:</strong>Male</div>',
    '      <div class="info-item"><strong>Age:</strong>29 years old</div>',
    '      <div class="info-item"><strong>Education:</strong>Bachelor\'s Degree</div>',
    '      <div class="info-item"><strong>University:</strong>Central South University</div>',
    '      <div class="info-item"><strong>Major:</strong>Information and Computational Science</div>',
    '      <div class="info-item"><strong>Work Experience:</strong>6 years</div>',
    '      <div class="info-item"><strong>Position:</strong>Java P6 & React+TS+Nextjs+Nestjs(Hono.js) Full-stack Developer</div>',
    '      <div class="info-item"><strong>Expected Salary:</strong>20k~25k CNY/month (before tax)</div>',
    "    </div>",
    "    <br/>",
    '    <div class="contact-info">',
    "    <h2>Contact Information</h2>",
    '      <div class="info-item"><strong>Phone:</strong>17363859671</div>',
    '      <div class="info-item"><strong>Email:</strong>aspirelisi@gmail.com (392710909@qq.com)</div>',
    '      <div class="info-item"><strong>WeChat:</strong>17363859671</div>',
    '      <div class="info-item"><strong>QQ:</strong>392710909</div>',
    "    </div>",
    "  </div>",
    "",
    "    <br/>",
    '  <div class="content-section">',
    "    <h2>Skills</h2>",
    "    <br/>",
    '    <div class="skills-grid">',
    '      <div class="skill-category">',
    "        <h3>System Architecture</h3>",
    "        <ul>",
    "          <li>Extensive experience in system modular design, microservice splitting and transformation, with solid understanding of system architecture scaling</li>",
    "          <li>Experienced in distributed service development and maintenance</li>",
    "          <li>Capable of handling ultra-large scale user and data volume system development</li>",
    "          <li>Strong ability to break down and decompose complex systems and requirements</li>",
    "          <li>Rich experience in large-scale to-C business requirement development</li>",
    "        </ul>",
    "      </div>",
    "    <br/>",
    '      <div class="skill-category">',
    "        <h3>Backend Technologies</h3>",
    "        <ul>",
    "          <li>Proficient in Spring Cloud ecosystem for microservice design and development</li>",
    "          <li>Expert in Java programming language, understanding JVM internals, familiar with multi-threading programming with practical experience</li>",
    "          <li>Proficient in Spring, SpringMVC, MyBatis development frameworks, familiar with SpringBoot framework</li>",
    "          <li>Expert in MySQL database usage with analysis and optimization experience, familiar with master-slave and high availability architecture</li>",
    "          <li>Familiar with NoSQL database MongoDB, with sharding and partitioning practical experience</li>",
    "          <li>Familiar with Redis, with related best practices and optimization experience</li>",
    "          <li>Familiar with Kafka message queue principles and usage scenarios</li>",
    "          <li>Familiar with distributed task scheduling framework Quartz</li>",
    "        </ul>",
    "      </div>",
    "    <br/>",

    '      <div class="skill-category">',
    "        <h3>Frontend Technologies</h3>",
    "        <ul>",
    "          <li>Familiar with React+TS+Nextjs+Nestjs(Hono.js) full-stack independent development</li>",
    "        </ul>",
    "      </div>",
    "    <br/>",

    '      <div class="skill-category">',
    "        <h3>Development Tools</h3>",
    "        <ul>",
    "          <li>Proficient in Eclipse/IntelliJ IDEA programming tools with good programming habits</li>",
    "          <li>Proficient in PowerDesigner modeling tool for database-related modeling with good specification habits</li>",
    "          <li>Proficient in Chrome and other tools for code debugging</li>",
    "          <li>Proficient in Git version control tool usage with good practices</li>",
    "          <li>Familiar with SecureCRT tool, basic Linux commands, log tracking and searching specifications</li>",
    "        </ul>",
    "      </div>",
    "    <br/>",

    '      <div class="skill-category">',
    "        <h3>Other Skills</h3>",
    "        <ul>",
    "          <li>Familiar with distributed service registration and discovery centers Zookeeper, Consul principles and usage</li>",
    "          <li>Understanding of Docker, Rancher basic usage and deployment operations</li>",
    "          <li>Familiar with small to medium enterprise scale server setup and deployment construction</li>",
    "        </ul>",
    "      </div>",
    "    </div>",
    "  </div>",
    "",
    "    <br/>",

    '  <div class="content-section">',
    "    <h2>Work Experience</h2>",
    '    <div class="timeline">',
    '      <div class="timeline-item">',
    '        <div class="timeline-header">',
    "          <h3>Beilian Biotechnology</h3>",
    '          <span class="timeline-date">June 2024 ~ June 2025</span>',
    "        </div>",
    '        <div class="timeline-content">',
    "          <h4>Self-developed CRM</h4>",
    "          <ul>",
    "            <li>Led the development of self-developed CRM backend system, independently completed API admin web development</li>",
    "          </ul>",
    "        </div>",
    "      </div>",
    "",
    "    <br/>",
    '      <div class="timeline-item">',
    '        <div class="timeline-header">',
    "          <h3>Hunan Fumi Technology</h3>",
    '          <span class="timeline-date">June 2020 ~ December 2023</span>',
    "        </div>",
    '        <div class="timeline-content">',
    "          <h4>North American Securities Market Trading Platform (Tens of millions of users 7*24 hours asset trading platform)</h4>",
    "          <ul>",
    "            <li>Led the design and development of Webull app account system account opening and compliance business for North American securities market self-developed products, including user lifecycle management, multi-category trading permissions, compliance control, risk management, etc.</li>",
    "            <li>Participated in Webull billing, profit/loss, deposit/withdrawal and transfer system business development, interfacing with self-developed third-party clearing merchants, involving user asset transfer and profit/loss calculation, bill generation, etc.</li>",
    "            <li>Participated in company-level self-developed clearing merchant migration project, platform-wide million-level user migration transformation</li>",
    "            <li>Participated in trading order placement chain refactoring and transformation development, due to business expansion needs, overall architecture adjustment and upgrade of old business systems and necessary legacy chain migration transformation</li>",
    "            <li>Participated in system unitization (supporting unlimited horizontal business expansion) transformation and upgrade development, to adapt to ultra-large scale user horizontal expansion, reduce system operating costs, solve middleware horizontal expansion issues, and disaster recovery needs</li>",
    "            <li>Led 7.0 gateway interface upgrade project, interfacing with company client teams including iOS, Android, H5, Qt, Web multi-terminal various business scenario interface refactoring, migration, and integration work</li>",
    "            <li>Led the design and development of company's Canada regional business expansion account system, including account, permission control, risk control related business</li>",
    "          </ul>",
    "        </div>",
    "      </div>",
    "",
    "    <br/>",

    '      <div class="timeline-item">',
    '        <div class="timeline-header">',
    "          <h3>Hunan Caohua Interactive Network Technology Co., Ltd.</h3>",
    '          <span class="timeline-date">March 2018 ~ March 2020</span>',
    "        </div>",
    '        <div class="timeline-content">',
    "          <h4>Ad Delivery System Project (Million-level mobile game platform)</h4>",
    "          <ul>",
    "            <li>Participated in interfacing with 30+ media advertising service providers including Toutiao, Tencent GuangDianTong, Baidu, UC to build an integrated delivery platform, the system was recognized by media such as Toutiao and ranked at the forefront of the industry</li>",
    "            <li>Led the development and maintenance of third-party media advertising data monitoring service (daily average PV 6M+, peak 70M+)</li>",
    "            <li>In 2019, as a core programmer of the project team, participated in the development and maintenance of the company's delivery system business. Not only completed internal management system version iteration requirements, but also analyzed existing system implementation during development intervals. Optimized online ad click monitoring business Redis cluster memory exceeding 65%. And without affecting the existing system, combined with MongoDB to extend click matching data retention from 1 day to 7 days, effectively improving click attribution rate.</li>",
    "            <li>Led the development and maintenance of company crawler system, proficient in using jsoup and other crawler frameworks and automated testing frameworks, familiar with business data tracking and collection processes</li>",
    "            <li>Led the development and construction of company DMP automation system from scratch, participated in iterative maintenance of company data warehouse project, familiar with Hadoop and Hive big data component business data cleaning processes</li>",
    "            <li>Led technical backend statistics related data audit business, proficient in using SQL for data statistics verification</li>",
    "          </ul>",
    "        </div>",
    "      </div>",
    "",
    "    <br/>",

    '      <div class="timeline-item">',
    '        <div class="timeline-header">',
    "          <h3>Hunan Ruiyao Network Technology Co., Ltd.</h3>",
    '          <span class="timeline-date">April 2017 ~ March 2018</span>',
    "        </div>",
    '        <div class="timeline-content">',
    "          <h4>Yaoyide APP Backend Management System Project</h4>",
    "          <ul>",
    "            <li>Participated in App data backend management system data service development and related traceability solution design</li>",
    "            <li>Led the design and development of management system pharmaceutical encyclopedia and other modules</li>",
    "            <li>Used caching and CDN acceleration to greatly improve pharmaceutical encyclopedia loading speed</li>",
    "          </ul>",
    "        </div>",
    "      </div>",
    "    </div>",
    "  </div>",
    "",
    "    <br/>",
    '  <div class="content-section">',
    "    <h2>Personal Traits</h2>",
    '    <ul class="personal-traits">',
    "      <li>Outgoing personality, generous and talkative, with good communication skills, love sharing, patient, good at teaching</li>",
    "      <li>Good stress resistance, don't blame others or avoid problems when encountering difficulties</li>",
    "      <li>Love technology, excellent requirement analysis and expression abilities, strong learning and adaptation capabilities</li>",
    "      <li>Strong sense of responsibility and good team collaboration spirit</li>",
    "      <li>Love sharing, have shared business and technical insights within teams</li>",
    "      <li>Wide range of interests (travel, photography, ultimate frisbee sports, etc.)</li>",
    "    </ul>",
    "  </div>",
    "</div>",
  ];
}
